# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# Message locale.
lang: en

# Enable the attachment item box.
enableAttachment: true

# Enable mail sending fee.
enableSendFee: false

# Sending fee per a mail.
sendFee: 10

# Attaching fee per an item.
attachFee: 10

# Enable to send mail to oneself.
enableSendSelf: false

# World names that disable to open attachment item box.
disableWorldsToOpenAttachBox: []

# Attachment item box line size. Please set 1 - 6.
# ex) 1 ->  you can attach 9 items per 1 mail.
# ex) 6 ->  you can attach 54 items per 1 mail.
attachBoxSize: 1

# Display empty line count before display UI.
uiEmptyLines: 3

# Enable to use player list.
enablePlayerList: true
