# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# メッセージの言語
lang: ja

# メールを作成したりアイテムを添付したりするために料金を必要とするか。
# 経済プラグインとVaultが導入されている必要があります。
enableSendFee: false

# メールを1通作成する料金です。
sendFee: 10

# メールにアイテムを1個添付する料金です。
attachFee: 10

# 自分自身に送信可能とするかどうか。
enableSendSelf: false

# メールの添付ボックスを操作不可に設定したいワールドを指定します。
# 例えば disableWorldsToOpenAttachment: ['sozai']  と設定すると、
# sozaiというワールド名に居るプレイヤーは、送信メールの添付ボックスや
# 受信したメールの添付ボックスを開くことができなくなります。
disableWorldsToOpenAttachBox: []

# メールの添付ボックスのサイズを指定します。
# 1列（＝9個）から6列（＝54個）まで指定可能です。
attachBoxSize: 1


