# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# -------------------- Misc --------------------

# Message locale.
lang: en

# Enable to send mail to oneself.
enableSendSelf: false

# Display empty line count before display UI.
uiEmptyLines: 2

# Enable to use player list address book.
enablePlayerList: false

# Limitation number of mail destination.
maxDestination: 10

# Limitation number of mail destination group.
maxDestinationGroup: 3

# Mail store period.
# If you set 30, the system deletes mails that 31 days passed from sending.
mailStorageTermDays: 30

# -------------------- Attachment Item Box --------------------

# Enable the attachment item box.
enableAttachment: true

# Attachment item box line size. Please set 1 - 6.
# ex) 1 ->  you can attach 9 items per 1 mail.
# ex) 6 ->  you can attach 54 items per 1 mail.
attachBoxSize: 1

# Max usage count of attachment item box per a player.
maxAttachmentBoxCount: 3

# World names that disable to open attachment item box.
disableWorldsToOpenAttachBox: []

# -------------------- C.O.D. Setting --------------------

# Enable C.O.D. money feature by using currency of economy plugin.
# If you want to use C.O.D. money feature, you need Vault and any economy plugin.
enableCODMoney: true

# Enable C.O.D. item feature.
enableCODItem: true

# When paying cash on delivery fee to the other player,
#   if the amount of post-payment does not match, you can set whether an error.
# In such Essentials "max-money" setting, if you have set the upper limit of money,
#   payment will be disappear. So please make this setting to true, for saving payment.
# If you are using such as taking a tax on payment in your economy plugin,
#   so you will not be able to remittances, please make this setting to false.
depositErrorOnUnmatch: true

# -------------------- Send Fee --------------------

# Enable mail sending fee.
enableSendFee: false

# Sending fee per a mail.
sendFee: 10

# Attaching fee per an item.
attachFee: 10

# COD money tax. Please specify parcentage.
# If you set "codMoneyTax: 10", and one of player set $300 as COD,
#   this player need to pay the additional sending fee $30 (= $300 * 10%).
codMoneyTax: 0

# COD item tax. Please specify price per item amount.
# If you set "codItemTax: 10", and one of player set DIAMOND * 8 as COD,
#   this player need to pay the additional sending fee $80 (= $10 * 8).
codItemTax: 0

# -------------------- Mail Group --------------------

# Max group creation num per a player.
maxCreateGroup: 5

# Max member num per a group.
maxGroupMember: 15

# Default mode of send mail permission.
# OP: only OP can send mail to this group.
# OWNER: owner and OP can send mail to this group.
# MEMBER: group members anyone can send mail to this group.
# EVERYONE: everyone can send mail to this group.
sendModeDefault: MEMBER

# Default mode of members modification.
# OP: only OP can add/remove members.
# OWNER: owner and OP can add/remove members.
# MEMBER: group members anyone can add/remove members.
# EVERYONE: everyone can add/remove members.
modifyModeDefault: OWNER

# Default mode of dissolution.
# OP: only OP can break-up group.
# OWNER: owner and OP can break-up group.
# MEMBER: group members anyone can break-up group.
# EVERYONE: everyone can break-up group.
dissolutionModeDefault: OWNER

# Sending permission mode of special group "All" (all players group).
specialGroupAllSendMode: OP

