# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# -------------------- 共通設定 --------------------

# メッセージの言語
lang: ja

# 自分自身に送信可能とするかどうか。
enableSendSelf: false

# UIを表示する系統のコマンドを実行したときに、
# UIの前に挿入する空行の行数を設定します。
# 0から9まで指定可能です。
uiEmptyLines: 2

# プレイヤー名簿を利用するかどうか。
# プレイヤー名簿では、サーバーに１度でも接続したことがあるプレイヤー全てが
# 一覧にリストアップされます。
enablePlayerList: true

# -------------------- アイテム添付設定 --------------------

# メールにアイテムの添付を可能にするかどうか。
enableAttachment: true

# メールの添付ボックスのサイズを指定します。
# 1列（＝9個）から6列（＝54個）まで指定可能です。
attachBoxSize: 1

# 同時に使用可能な添付ボックスの個数を指定します。
maxAttachmentBoxCount: 3

# メールの添付ボックスを操作不可に設定したいワールドを指定します。
# 例えば disableWorldsToOpenAttachment: ['sozai']  と設定すると、
# sozaiというワールド名に居るプレイヤーは、送信メールの添付ボックスや
# 受信したメールの添付ボックスを開くことができなくなります。
disableWorldsToOpenAttachBox: []

# -------------------- 送信料金設定 --------------------

# メールを作成したりアイテムを添付したりするために料金を必要とするかどうか。
# 経済プラグインとVaultが導入されている必要があります。
enableSendFee: false

# 1つの宛先にメールを作成する料金です。
# 送信先が複数ある場合は、送信先の数だけ倍になります。
sendFee: 10

# メールにアイテムを1個添付する料金です。
attachFee: 10

# -------------------- メールグループ設定 --------------------

# 1プレイヤーが作成可能なグループの最大数。
# OPや、'undine.group.infinite-create'パーミッションを持った人は、
# この数値に関係なく無限に作成可能です。
maxCreateGroup: 5

# 1グループに追加できる最大プレイヤー数
# OPや、'undine.group.infinite-add-member'パーミッションを持った人は、
# この数値に関係なく無限に追加可能です。
maxGroupMember: 15

# グループへのメール送信権限のデフォルト
# OP → OPのみがグループへメール送信可能
# OWNER → オーナーとOPがグループへメール送信可能
# MEMBER → メンバーならグループへメール送信可能
# EVERYONE → 誰でもグループへメール送信可能
sendModeDefault: MEMBER

# グループのメンバー変更権限のデフォルト
# OP → OPのみが変更可能
# OWNER → オーナーとOPが変更可能
# MEMBER → メンバーなら変更可能
# EVERYONE → 誰でも変更可能
modifyModeDefault: OWNER

# グループの解散権限のデフォルト
# OP → OPのみが解散可能
# OWNER → オーナーとOPが解散可能
# MEMBER → メンバーなら解散可能
# EVERYONE → 誰でも解散可能
dissolutionModeDefault: OWNER
