# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2015

# -------------------- Misc --------------------

# Message locale.
lang: en

# Enable to send mail to oneself.
enableSendSelf: false

# Display empty line count before display UI.
uiEmptyLines: 2

# Enable to use player list address book.
enablePlayerList: true

# -------------------- Attachment Item Box --------------------

# Enable the attachment item box.
enableAttachment: true

# Attachment item box line size. Please set 1 - 6.
# ex) 1 ->  you can attach 9 items per 1 mail.
# ex) 6 ->  you can attach 54 items per 1 mail.
attachBoxSize: 1

# Max usage count of attachment item box per a player.
maxAttachmentBoxCount: 3

# World names that disable to open attachment item box.
disableWorldsToOpenAttachBox: []

# -------------------- Send Fee --------------------

# Enable mail sending fee.
enableSendFee: false

# Sending fee per a mail.
sendFee: 10

# Attaching fee per an item.
attachFee: 10

# -------------------- Mail Group --------------------

# Max group creation num per a player.
maxCreateGroup: 5

# Max member num per a group.
maxGroupMember: 15

# Default mode of send mail permission.
# OP: only OP can send mail to this group.
# OWNER: owner and OP can send mail to this group.
# MEMBER: group members anyone can send mail to this group.
# EVERYONE: everyone can send mail to this group.
sendModeDefault: MEMBER

# Default mode of members modification.
# OP: only OP can add/remove members.
# OWNER: owner and OP can add/remove members.
# MEMBER: group members anyone can add/remove members.
# EVERYONE: everyone can add/remove members.
modifyModeDefault: OWNER

# Default mode of dissolution.
# OP: only OP can break-up group.
# OWNER: owner and OP can break-up group.
# MEMBER: group members anyone can break-up group.
# EVERYONE: everyone can break-up group.
dissolutionModeDefault: OWNER
