name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.undine.Undine
Description: Undine Mail Plugin
author: ucchy

commands:
  undine:
    description: Commands of Undine
    aliases: [mail,umail]
    usage: |
           /<command> inbox [page] - Check your unread mails.
           /<command> outbox [page] - Check your sent mails.
           /<command> read <index> - Opens the specified mail.
           /<command> text <to> <message> - Send simple text mail.
           /<command> write - Enter to mail creation mode.
           /<command> to <line num> <to> - Change the destination of mail.
           /<command> to delete <line num> - Delete the destination of mail.
           /<command> message <line num> <message> - Change the message of mail.
           /<command> message delete <line num> - Delete the message of mail.
           /<command> attach [index] - Open attachment box of mail.
           /<command> send - Send mail.
           /<command> cancel - Cancel to mail creation mode.
           /<command> reload - Reload all of data.
    permission: undine.command
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  undine.command:
    description: Permission of command.
    default: true
  undine.command.inbox:
    description: Permission of inbox command.
    default: true
  undine.command.outbox:
    description: Permission of outbox command.
    default: true
  undine.command.read:
    description: Permission of read command.
    default: true
  undine.command.read-all:
    description: Permission of read other's mail.
    default: op
  undine.command.text:
    description: Permission of text command.
    default: true
  undine.command.write:
    description: Permission of write command.
    default: true
  undine.command.to:
    description: Permission of to command.
    default: true
  undine.command.message:
    description: Permission of message command.
    default: true
  undine.command.attach:
    description: Permission of attach command.
    default: true
  undine.command.send:
    description: Permission of send command.
    default: true
  undine.command.send-all:
    description: Permission of send all command.
    default: op
  undine.command.cancel:
    description: Permission of send command.
    default: true
  undine.command.reload:
    description: Permission of reload command.
    default: op
  'undine.command.*':
    description: Permissions of all commands.
    children:
      undine.command: true
      undine.command.inbox: true
      undine.command.outbox: true
      undine.command.read: true
      undine.command.read-all: true
      undine.command.text: true
      undine.command.write: true
      undine.command.to: true
      undine.command.message: true
      undine.command.attach: true
      undine.command.send: true
      undine.command.send-all: true
      undine.command.cancel: true
      undine.command.reload: true

  undine.multi-attach:
    description: Permission of sending multi attachment mail.
    default: op

  'undine.*':
    undine: All Permissions of Undine.
    children:
      'undine.command.*': true
      undine.multi-attach: true


