name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.mm.MagicMail
Description: Mail Plugin
author: ucchy

commands:
  magicmail:
    description: Commands of MagicMail
    aliases: [mm,mail]
    usage: |
           /<command> inbox [page] - Check your unread mails.
           /<command> outbox [page] - Check your sent mails.
           /<command> read <index> - Opens the specified mail.
           /<command> text <to> <message> - Send simple text mail.
           /<command> write - Enter to mail creation mode.
           /<command> to <line num> <to> - Change the destination of mail.
           /<command> to delete <line num> - Delete the destination of mail.
           /<command> message <line num> <message> - Change the message of mail.
           /<command> message delete <line num> - Delete the message of mail.
           /<command> attach [index] - Open attachment box of mail.
           /<command> send - Send mail.
           /<command> cancel - Cancel to mail creation mode.
           /<command> reload - Reload all of data.
    permission: magicmail.command
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  magicmail.command:
    description: Permission of command.
    default: true
  magicmail.command.inbox:
    description: Permission of inbox command.
    default: true
  magicmail.command.outbox:
    description: Permission of outbox command.
    default: true
  magicmail.command.read:
    description: Permission of read command.
    default: true
  magicmail.command.read-all:
    description: Permission of read other's mail.
    default: op
  magicmail.command.text:
    description: Permission of text command.
    default: true
  magicmail.command.write:
    description: Permission of write command.
    default: true
  magicmail.command.to:
    description: Permission of to command.
    default: true
  magicmail.command.message:
    description: Permission of message command.
    default: true
  magicmail.command.attach:
    description: Permission of attach command.
    default: true
  magicmail.command.send:
    description: Permission of send command.
    default: true
  magicmail.command.send-all:
    description: Permission of send all command.
    default: op
  magicmail.command.cancel:
    description: Permission of send command.
    default: true
  magicmail.command.reload:
    description: Permission of reload command.
    default: op
  'magicmail.command.*':
    description: Permissions of all commands.
    children:
      magicmail.command: true
      magicmail.command.inbox: true
      magicmail.command.outbox: true
      magicmail.command.read: true
      magicmail.command.read-all: true
      magicmail.command.text: true
      magicmail.command.write: true
      magicmail.command.to: true
      magicmail.command.message: true
      magicmail.command.attach: true
      magicmail.command.send: true
      magicmail.command.send-all: true
      magicmail.command.cancel: true
      magicmail.command.reload: true

  magicmail.multi-attach:
    description: Permission of sending multi attachment mail.
    default: op

  'magicmail.*':
    description: All Permissions of MagicMail.
    children:
      'magicmail.command.*': true
      magicmail.multi-attach: true


