name: ${project.name}
version: ${project.version}
main: org.bitbucket.ucchy.undine.UndineMailer
description: UndineMailer - Mail Plugin for ${release.lang}
softdepend: [Vault]
author: ucchy

commands:
  undine:
    description: Command of UndineMailer
    aliases: [mail,umail]
    usage: |
           /<command> inbox [page] - Check your unread mails.
           /<command> outbox [page] - Check your sent mails.
           /<command> read <index> - Opens the specified mail.
           /<command> text <to> <message> - Send simple text mail.
           /<command> write - Enter to mail creation mode.
           /<command> to <line num> <to> - Change the destination of mail.
           /<command> to delete <line num> - Delete the destination of mail.
           /<command> message <line num> <message> - Change the message of mail.
           /<command> message delete <line num> - Delete the message of mail.
           /<command> attach [index] - Open attachment box of mail.
           /<command> costmoney <amount> - Set fee that cost money on opening box.
           /<command> costitem <item[:amount]> - Set fee that cost item on opening box.
           /<command> send - Send mail.
           /<command> cancel - Cancel to mail creation mode.
           /<command> reload - Reload all of data.
    permission: undine.command
    permission-message: 'You don''t have a permission "<permission>".'

  undinelist:
    description: Command of Player list
    aliases: [ulist,uindex]
    usage: |
           /<command> - display player index button page.
           /<command> <pre> [page] - display players that starts with prefix.
    permission: undine.list
    permission-message: 'You don''t have a permission "<permission>".'

  undinegroup:
    description: Command of Mail group
    aliases: [ugroup]
    usage: |
           /<command> - display player index button page.
           /<command> <pre> [page] - display players that starts with prefix.
    permission: undine.group
    permission-message: 'You don''t have a permission "<permission>".'

permissions:
  undine.command:
    description: Permission of command.
    default: true
  undine.inbox:
    description: Permission of inbox command.
    default: true
  undine.outbox:
    description: Permission of outbox command.
    default: true
  undine.read:
    description: Permission of read command.
    default: true
  undine.read-all:
    description: Permission of read other's mail.
    default: op
  undine.text:
    description: Permission of text command.
    default: true
  undine.write:
    description: Permission of write command.
    default: true
  undine.to:
    description: Permission of to command.
    default: true
  undine.message:
    description: Permission of message command.
    default: true
  undine.attach:
    description: Permission of attach command.
    default: true
  undine.attach-all:
    description: Permission of opening other's mail attach box.
    default: op
  undine.costmoney:
    description: Permission of costmoney command.
    default: true
  undine.costitem:
    description: Permission of costitem command.
    default: true
  undine.send:
    description: Permission of send command.
    default: true
  undine.cancel:
    description: Permission of send command.
    default: true
  undine.reload:
    description: Permission of reload command.
    default: op
  undine.list:
    description: Permission of list command.
    default: true
  undine.group:
    description: Permission of group command.
    default: true
  'undine.*':
    description: All Permissions of UndineMailer.
    children:
      undine.command: true
      undine.inbox: true
      undine.outbox: true
      undine.read: true
      undine.read-all: true
      undine.text: true
      undine.write: true
      undine.to: true
      undine.message: true
      undine.attach: true
      undine.attach-all: true
      undine.costmoney: true
      undine.costitem: true
      undine.send: true
      undine.cancel: true
      undine.reload: true
      undine.list: true
      undine.group: true
